# Generated by Django 3.0.2 on 2020-05-22 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0001_initial'),
        ('tracks', '0004_auto_20200421_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='engineer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='engineers.Engineer'),
            preserve_default=False,
        ),
    ]
