# Generated by Django 3.0.2 on 2020-04-28 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='delay_changes',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='How much to increase/reduce the delay?'),
        ),
        migrations.AddField(
            model_name='revision',
            name='distortion_changes',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='How much to raise/reduce the distortion?'),
        ),
        migrations.AddField(
            model_name='revision',
            name='eq_high',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='How much to raise/reduce the highs?'),
        ),
        migrations.AddField(
            model_name='revision',
            name='eq_low',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='How much to raise/reduce the lows?'),
        ),
        migrations.AddField(
            model_name='revision',
            name='eq_middle',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='How much to raise/reduce the middle?'),
        ),
        migrations.AddField(
            model_name='revision',
            name='reverb_changes',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='How much to increase/reduce the reverb?'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='additionalcomments',
            field=models.TextField(blank=True, default='None', verbose_name='Please leave additional comments'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='panningposition',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Position of an instrument/vocal in stereo field'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='volumechange',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='How much you want the volume to change?'),
        ),
    ]
