# Generated by Django 3.0.2 on 2020-05-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=32)),
                ('lastname', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=32)),
                ('vkid', models.IntegerField()),
                ('language', models.CharField(choices=[('eng', 'English'), ('fr', 'Française'), ('ru', 'Русский')], default='ru', max_length=32)),
            ],
        ),
    ]
